# Site settings
author: Olena
title: Hello world!
header-img: img/home-bg.png
email: eageeva@hotmail.com
copyright_name: Olena
description: > # this means to ignore newlines until "baseurl:"
  my coding adventure 
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  Mathwell

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
